services:
    job:
        image: postgres:17
        ports:
            - "5445:5432"
        environment:
            POSTGRES_USER: job
            POSTGRES_PASSWORD: job
            POSTGRES_DB: job
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql